# Generated by Django 4.2.2 on 2023-06-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('Titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('Portada', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('Album', models.CharField(max_length=50)),
                ('Autor', models.CharField(max_length=50)),
            ],
        ),
    ]
