# Generated by Django 4.2.2 on 2023-06-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rfc', models.CharField(default='', max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='Album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='Portada',
            new_name='portada',
        ),
        migrations.RenameField(
            model_name='cancion',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='Autor',
        ),
        migrations.AddField(
            model_name='cancion',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='tienda.autor'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tienda.genero'),
        ),
    ]
