# Generated by Django 4.2.2 on 2023-06-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='idAutor',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='idGen',
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='portada',
            field=models.ImageField(upload_to='imagenes/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
