# Generated by Django 4.2.2 on 2023-06-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_autor_idautor_remove_genero_idgen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='idAutor',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='genero',
            name='idGen',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
